### ISSUE TITLE
Naming: Change Optimizer to Solver again

### ISSUE THREAD

**Issue by MarvinTeichmann** [TensorVision/TensorVision#10]
Solver seems to be the name of class/code to handle training. (In Caffe and Code/Libs inspired by Caffe). See Karpathy Lecture on [Frameworks](https://youtu.be/Vf_-OkqbwPo?t=5m54s). Should we switch back calling the module solver?

**Comment by MartinThoma** [comment]
I don't see any new information there since our last discussion. It does not matter too much how other frameworks call it. It should make most sense to us.

(And TensorFlow calls it optimizer ([source](https://www.tensorflow.org/versions/r0.8/api_docs/python/train.html#optimizers)), if that is important for you)

**Comment by MarvinTeichmann** [comment]
ok, then lets stick to the current name sheme.
